### ISSUE TITLE
ImportError: cannot import name 'BoilerMaxPowerIndex' from 'kospel_cmi.registers.enums' after updating to v1.1.0

### ISSUE THREAD

**Issue by lookasek** [JanKrl/ha-kospel-cmi#61]
**Describe the bug**
After updating the custom integration ha-kospel-cmi to version v1.1.0, the integration fails to load during Home Assistant startup. The issue seems to be caused by a missing or renamed BoilerMaxPowerIndex enum in the kospel_cmi.registers.enums module.

**Environment**
- Home Assistant version: 2026.7.2
- Integration version: v1.1.0
- Heater model: EKCO.M3
- Backend type: HTTP
- Installation method: HACS

**To Reproduce**
1. Update ha-kospel-cmi to version v1.1.0 via HACS.
2. Restart Home Assistant.
3. The integration fails to start, throwing an ImportError.

**Expected behavior**
The integration should load successfully after a restart without raising ImportError or event loop blocking warnings.

**Logs**
```
Logger: homeassistant.config_entries
Source: config_entries.py:798
First occurred: 21:40:17 (1 occurrences)
Last logged: 21:40:17

Error setting up entry Kospel Heater 192.168.8.62 (device 65) for kospel
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 798, in __async_setup_with_context
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/kospel/__init__.py", line 78, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2777, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
... (truncated for readability, full stack trace below) ...
  File "/config/custom_components/kospel/select.py", line 16, in <module>
    from kospel_cmi.registers.enums import BoilerMaxPowerIndex
ImportError: cannot import name 'BoilerMaxPowerIndex' from 'kospel_cmi.registers.enums' (/usr/local/lib/python3.14/site-packages/kospel_cmi/registers/enums.py)
```

```
Logger: homeassistant.util.loop
Source: util/loop.py:135
First occurred: 21:40:17 (1 occurrences)
Last logged: 21:40:17

Detected blocking call to import_module with args ('custom_components.kospel.select',) inside the event loop by custom integration 'kospel' at custom_components/kospel/__init__.py, line 78: await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS) (offender: /usr/src/homeassistant/homeassistant/loader.py, line 1321: return importlib.import_module(f"{self.pkg_path}.{platform_name}")), please create a bug report at https://github.com/JanKrl/ha-kospel-cmi/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module
```

**Comment by JanKrl** [comment]
Issue was caused by malfunctioning dependency library constraints in manifest.json.
Please update to [v1.1.1](https://github.com/JanKrl/ha-kospel-cmi/releases/tag/v1.1.1)
